import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider, Show, UserButton } from "@clerk/nextjs";
import { Button } from "@/components/ui/button";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <header className="fixed top-0 w-full z-0 border-b bg-white/80 backdrop-blur-md dark:bg-zinc-900/80 dark:border-zinc-800">
            <div className="flex justify-between max-w-7xl mx-auto px-4 h-16">
              <h1 className="text-xl font-bold">Vur3D</h1>
              <nav>
                <Show when="signed-out">
                  <Button variant={"outline"}>Sign In</Button>
                  <Button variant={"default"}>Sign Up</Button>
                </Show>
                <Show when="signed-in">
                  <UserButton />
                </Show>
              </nav>
            </div>
          </header>
          <div className="flex min-h-screen items-center justify-center bg-zinc-50 font-sans dark:bg-black">
            <main className="flex min-h-screen w-full max-w-3xl flex-col items-center justify-between py-32 px-16 bg-white dark:bg-black sm:items-start">
              {children}
            </main>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
